/**
 * Keyword / function / data-type vocabularies.
 *
 * These drive *casing* only. Decisions about line breaks and indentation live in
 * `formatter.ts`, which matches on its own clause tables. A word being absent
 * here never changes layout, it only means the word keeps the author's casing.
 */

const words = (s: string): string[] =>
    s.split(/\s+/u).map((w) => w.trim()).filter((w) => w.length > 0);

/** Keywords shared by every supported dialect. */
export const ANSI_KEYWORDS: string[] = words(`
    ADD ALL ALTER AND ANY AS ASC AUTHORIZATION BEGIN BETWEEN BY CASCADE CASE
    CHECK COLLATE COLUMN COMMIT CONSTRAINT CREATE CROSS CURRENT CURRENT_DATE
    CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER CURSOR DEALLOCATE DECLARE
    DEFAULT DELETE DESC DISTINCT DROP ELSE END ESCAPE EXCEPT EXECUTE EXISTS
    FETCH FILTER FOR FOREIGN FROM FULL FUNCTION GRANT GROUP HAVING IF IN INDEX
    INNER INSERT INTERSECT INTO IS JOIN KEY LEFT LIKE LIMIT MATCH NATURAL NOT
    NULL NULLS OF OFFSET ON ONLY OPEN OR ORDER OUTER OVER PARTITION PRIMARY
    PROCEDURE RECURSIVE REFERENCES RETURN RETURNS REVOKE RIGHT ROLLBACK ROW
    ROWS SELECT SET SOME TABLE TEMPORARY THEN TO TRANSACTION TRIGGER TRUNCATE
    UNION UNIQUE UNKNOWN UPDATE USER USING VALUES VIEW WHEN WHERE WHILE WINDOW
    WITH WITHIN
`);

/** Literals treated as keywords when `uppercaseBooleanLiterals` is on. */
export const BOOLEAN_LITERALS: string[] = words(`NULL TRUE FALSE`);

export const ANSI_FUNCTIONS: string[] = words(`
    ABS AVG CAST CEILING COALESCE CONCAT COUNT DENSE_RANK EXTRACT FIRST_VALUE
    FLOOR GREATEST LAG LAST_VALUE LEAD LEAST LEFT LENGTH LOWER LTRIM MAX MIN NTILE
    NULLIF POSITION POWER RANK RIGHT ROUND ROW_NUMBER RTRIM SQRT SUBSTRING SUM TRIM
    UPPER
`);

export const ANSI_DATA_TYPES: string[] = words(`
    BIGINT BINARY BIT BOOLEAN CHAR CHARACTER DATE DECIMAL DOUBLE FLOAT INT
    INTEGER INTERVAL NUMERIC PRECISION REAL SMALLINT TIME TIMESTAMP VARBINARY
    VARCHAR
`);

export const TSQL_KEYWORDS: string[] = words(`
    APPLY BACKUP BREAK BULK CATCH CHECKPOINT CLOSE CLUSTERED COMPUTE CONTINUE
    CONVERT DATABASE DBCC DENY DISK DISTRIBUTED DUMP ERRLVL EXEC EXIT EXTERNAL
    FILLFACTOR GO GOTO HOLDLOCK IDENTITY IDENTITYCOL IDENTITY_INSERT IF
    INCLUDE KILL LINENO LOAD MATCHED MAXDOP MERGE NATIONAL NOCHECK NOCOUNT
    NOLOCK
    NONCLUSTERED OFF OFFSETS OPENDATASOURCE OPENQUERY OPENROWSET OPENXML
    OPTION OUTPUT PERCENT PERSISTED PIVOT PLAN PRINT PROC PUBLIC RAISERROR
    READ READTEXT RECONFIGURE REPLICATION RESTORE RESTRICT REVERT ROWCOUNT
    ROWGUIDCOL RULE SAVE SCHEMA SECURITYAUDIT SEMANTICKEYPHRASETABLE SOURCE
    SETUSER SHUTDOWN STATISTICS TABLESAMPLE TEXTSIZE THROW TOP TRAN TRY
    TSEQUAL UNPIVOT UPDATETEXT USE VARYING WAITFOR WRITETEXT XACT_ABORT
`);

export const TSQL_FUNCTIONS: string[] = words(`
    CHARINDEX CHOOSE CONVERT DATALENGTH DATEADD DATEDIFF DATEFROMPARTS DATENAME
    IDENTITY
    DATEPART DAY EOMONTH ERROR_LINE ERROR_MESSAGE ERROR_NUMBER ERROR_PROCEDURE
    ERROR_SEVERITY ERROR_STATE FORMAT GETDATE GETUTCDATE HASHBYTES IIF ISDATE
    ISNULL ISNUMERIC JSON_VALUE LEN MONTH NEWID NEWSEQUENTIALID OBJECT_ID
    PARSENAME PATINDEX QUOTENAME REPLACE REPLICATE REVERSE SCOPE_IDENTITY
    SPACE STR STRING_AGG STRING_SPLIT STUFF SWITCHOFFSET SYSDATETIME
    SYSUTCDATETIME TRY_CAST TRY_CONVERT TRY_PARSE YEAR
`);

export const TSQL_DATA_TYPES: string[] = words(`
    DATETIME DATETIME2 DATETIMEOFFSET GEOGRAPHY GEOMETRY HIERARCHYID IMAGE
    MONEY NCHAR NTEXT NVARCHAR ROWVERSION SMALLDATETIME SMALLMONEY SQL_VARIANT
    TEXT TINYINT UNIQUEIDENTIFIER XML
`);

export const POSTGRES_KEYWORDS: string[] = words(`
    ANALYZE CONFLICT DO DOMAIN EXPLAIN EXTENSION ILIKE LANGUAGE LATERAL
    LOOP MATERIALIZED NOTHING NOTIFY OWNER PERFORM RAISE REFRESH REINDEX RETURNING
    SEQUENCE SIMILAR TABLESPACE UNLOGGED VACUUM
`);

export const POSTGRES_FUNCTIONS: string[] = words(`
    ARRAY_AGG COALESCE GENERATE_SERIES JSONB_AGG JSONB_BUILD_OBJECT NOW
    REGEXP_MATCHES REGEXP_REPLACE STRING_AGG TO_CHAR TO_DATE TO_NUMBER
    TO_TIMESTAMP UNNEST
`);

export const POSTGRES_DATA_TYPES: string[] = words(`
    BIGSERIAL BOOL BPCHAR BYTEA CIDR CITEXT DATERANGE INET INT2 INT4 INT8
    JSON JSONB MONEY SERIAL TEXT TSQUERY TSVECTOR UUID VARBIT XML
`);

export const MYSQL_KEYWORDS: string[] = words(`
    ALGORITHM AUTO_INCREMENT CHANGE CHARSET DATABASES DELAYED DESCRIBE
    DUPLICATE ENGINE ENCLOSED EXPLAIN FIELDS FORCE FULLTEXT HIGH_PRIORITY
    IGNORE INFILE KEYS KILL LINES LOAD LOCK LOW_PRIORITY MODIFY OPTIMIZE
    OUTFILE REGEXP RENAME REPEAT REPLACE REQUIRE RLIKE SEPARATOR SHOW SPATIAL
    SQL_CALC_FOUND_ROWS STRAIGHT_JOIN TERMINATED UNLOCK UNSIGNED USE ZEROFILL
`);

export const MYSQL_FUNCTIONS: string[] = words(`
    CONCAT_WS CURDATE CURTIME DATE_ADD DATE_FORMAT DATE_SUB GROUP_CONCAT IFNULL
    JSON_EXTRACT LOCATE NOW STR_TO_DATE UNIX_TIMESTAMP UUID
`);

export const MYSQL_DATA_TYPES: string[] = words(`
    BLOB DATETIME ENUM LONGBLOB LONGTEXT MEDIUMBLOB MEDIUMINT MEDIUMTEXT SET
    TEXT TINYBLOB TINYINT TINYTEXT YEAR
`);

export const SQLITE_KEYWORDS: string[] = words(`
    ABORT ATTACH AUTOINCREMENT CONFLICT DETACH EXCLUSIVE FAIL GLOB IMMEDIATE
    INDEXED INSTEAD PRAGMA QUERY RAISE REGEXP REINDEX REPLACE VACUUM VIRTUAL
`);

export const SQLITE_DATA_TYPES: string[] = words(`BLOB TEXT`);

export const ORACLE_KEYWORDS: string[] = words(`
    BODY CONNECT DECODE DUAL ELSIF EXCEPTION LOOP MINUS MODEL NOCYCLE
    NOWAIT PACKAGE PIPELINED PRAGMA PRIOR RAISE REF RETURNING REVERSE ROWNUM
    SIBLINGS START SYNONYM TYPE VARRAY
`);

export const ORACLE_FUNCTIONS: string[] = words(`
    ADD_MONTHS INSTR LISTAGG LPAD NVL NVL2 RPAD SYSDATE TO_CHAR TO_DATE
    TO_NUMBER TRUNC
`);

export const ORACLE_DATA_TYPES: string[] = words(`
    BINARY_DOUBLE BINARY_FLOAT BLOB CLOB LONG NCLOB NUMBER PLS_INTEGER RAW
    ROWID UROWID VARCHAR2
`);
