/**
 * Browser entry point for the settings playground artifact. Exposes the real
 * formatter so the page's before/after examples are generated by the same
 * engine the extension uses, not transcribed by hand.
 */
import { formatSql } from '../src/formatter/formatter';
import { DEFAULT_OPTIONS } from '../src/formatter/options';

(globalThis as unknown as Record<string, unknown>).SqlFormatter = {
    formatSql,
    DEFAULT_OPTIONS,
};
